devmode = false

[log]
  file = ""

[proxy]
  whisper = "http://127.0.0.1:9090/"
  chat = "http://127.0.0.1:9190/"
  emotion = "http://127.0.0.1:9290/"
  diffusion = "http://127.0.0.1:9390/"
  #spleeter = "http://127.0.0.1:9490/"
  # threed = "http://127.0.0.1:9590/"

[srv]
  host = "0.0.0.0"
  port = 8080
  # IPs exempt from ratelimiting.
  ratelimit_exempt = [
    "192.168.0.0/16",
  ]
  trusted_proxies = [
    "127.0.0.1"
  ]
  api_version = "1.0.0"

[pages]
  frontend_version = "1.0.0"